server:
  port: 8000
spring:
  datasource:
    url: ${vcap.services.cleardb.credentials.jdbcUrl}
    username: ${vcap.services.cleardb.credentials.username}
    password: ${vcap.services.cleardb.credentials.password}
  jpa:
    hibernate:
      ddl-auto: create
cnj:
  info:
    message: Server verwendet Konfiguration aus Codebase!