server:
  port: 8000
spring:
#  datasource:
#    url: ${cloud.services.cleardb.credentials.jdbcUrl}
#    username: ${cloud.services.cleardb.credentials.username}
#    password: ${cloud.services.cleardb.credentials.password}
  jpa:
    hibernate:
      ddl-auto: create
cnj:
  info:
    message: Server verwendet Konfiguration aus Codebase!