server:
  port: 8000
spring:
  datasource:
    url: ${cloud.services.cleardb.connection.jdbcUrl}
    username: ${cloud.services.cleardb.connection.username}
    password: ${cloud.services.cleardb.connection.password}
  jpa:
    hibernate:
      ddl-auto: create
cnj:
  info:
    message: Server verwendet Konfiguration aus Codebase!