server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-sl-dfw-01.cleardb.net/ibmx_6ed39368204a928?user=b0711bc68ade87&password=dbaebf34
    username: b0711bc68ade87
    password: dbaebf34
  jpa:
    hibernate:
      ddl-auto: create
cnj:
  info:
    message: Server verwendet Konfiguration aus Codebase!